name: Send Telegram Messages

on:
  workflow_dispatch:  # Menjalankan workflow secara manual
  schedule:
    - cron: "0 * * * *"  # Menjalankan setiap jam, jika diperlukan

jobs:
  sendMessages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install telethon

      - name: Run Python script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_NAME: ${{ secrets.SESSION_NAME }}
        run: python send_message.py
