name: Scheduled Telegram Posting

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  sendMessages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Updated to a compatible version

      - name: Install dependencies
        run: pip install telethon

      - name: Decode and save session file
        env:
          SESSION_BASE64: ${{ secrets.SESSION_BASE64 }}
        run: |
          echo "$SESSION_BASE64" | base64 --decode > my_session.session

      - name: Run Python script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_NAME: my_session
        run: python send_message.py
